import {
  AppBar,
  Box,
  Container,
  IconButton,
  Typography,
  Toolbar,
} from "@mui/material";

import Head from "next/head";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Next + MUI Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: "flex" }}>
        <AppBar component="nav">
          <Toolbar>
            <IconButton
              color="inherit"
              aria-label="open drawer"
              edge="start"
              sx={{ mr: 2, display: { sm: "none" } }}
            ></IconButton>
            <Typography
              variant="h6"
              component="div"
              sx={{ flexGrow: 1, display: { xs: "none", sm: "block" } }}
            >
              MUI
            </Typography>
          </Toolbar>
        </AppBar>
      </Box>

      <Container
        component="main"
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "90vh",
        }}
      >
        <Typography variant="h1">
          Welcome to <a href="https://nextjs.org">Next.js + MUI!</a>
        </Typography>
      </Container>

      <Container sx={{ display: "flex", justifyContent: "center" }}>
        <Typography variant="body2">Made with ❤️❤️❤️</Typography>
      </Container>
    </Container>
  );
}
